"""
models — Electrochemical, transport, transient pulse, and techno-economic modeling for aqueous electrowinning.
"""

from .electrochemistry import (
    CellVoltageModel,
    specific_energy_kWh_per_kg,
    specific_energy_kWh_per_t,
    production_rate_kg_per_hr,
    current_density_to_production,
)
from .pourbaix import (
    FePourbaix,
    her_line,
    oer_line,
    nernst_pH_line,
)
from .kinetics import (
    DepositionKinetics,
    TafelBranch,
    limiting_current_density,
)
from .boundary_layer import (
    CathodeBoundaryLayer,
    BoundaryLayerState,
)
from .transport import (
    NernstPlanckFilm,
    NernstPlanckState,
    FilmProfile,
    compare_support_levels,
)
from .pulse import (
    PulseDepositionModel,
    PulseWaveform,
    PulseResult,
    compare_dc_vs_pulse,
)
from .eis import (
    RandlesFit,
    load_spectrum,
    summarize_spectrum,
    cpe_impedance,
    warburg_impedance,
    randles_impedance,
    randles_cpe_impedance,
    fit_randles_spectrum,
    exchange_current_from_rct,
    synthetic_randles_spectrum,
)
from .hull_cell import (
    HullCellGeometry,
    GravimetricFEResult,
    hull_current_distribution,
    summarize_hull_distribution,
    current_density_window,
    load_galvanostatic_trace,
    load_gravimetry,
    cathodic_charge_C,
    gravimetric_faradaic_efficiency,
    analyze_gravimetric_efficiency,
)
from .technoeconomic import (
    ElectrolyzerParams,
    CAPEXModel,
    OPEXModel,
    LevelizedCost,
    sensitivity_analysis,
    compare_routes,
    BENCHMARK_COSTS,
)
from .anode import (
    AnodeKinetics,
    AnodeMaterial,
    DSA_IRO2_TA2O5,
    NICO_SPINEL,
    NIFE_LDH,
    PT_TI,
    bubble_fraction,
    bubble_resistance_multiplier,
    concentration_overpotential_oer,
    full_cell_voltage,
    anode_eta_from_lookup,
    E0_OER_ACIDIC,
    E0_OER_ALKALINE,
    E0_CER,
)
from .co_deposition import (
    GuglielmiCarbonIncorporation,
    AnomalousFeNiKinetics,
    PhaseIIICoDeposition,
    build_phase3_model,
    surface_pH_from_current,
    surface_pH_from_pulse,
    effective_mass_transport_enhancement,
)
from .closed_loop import (
    AnodeDurabilityParams,
    ClosedLoopParams,
    PhaseIVOperatingPoint,
    PhaseIVResult,
    PhaseIVClosedLoop,
)
from .mechanical_properties import (
    MechanicalPropertiesModel,
    MechanicalPropertiesResult,
    MechanicalPropertiesParams,
    GrainSizeParams,
    estimate_grain_size_um,
    hall_petch_yield_MPa,
    solid_solution_strengthening_MPa,
    carbon_dispersion_strengthening_MPa,
    porosity_factor,
    build_mechanical_model_from_phase3_result,
)
from .process_flow import (
    generate_process_flow_diagram,
    generate_detailed_flow_with_composition,
)
from .carburization import (
    CarburizationModel,
    CarburizationParams,
    CarburizationProfile,
    CarburizationResult,
    carbon_diffusivity_m2_s,
    hardness_from_carbon_wt,
    tempered_hardness,
    estimate_carburizing_time_for_case_depth,
)

__all__ = [
    "CellVoltageModel",
    "specific_energy_kWh_per_kg",
    "specific_energy_kWh_per_t",
    "production_rate_kg_per_hr",
    "current_density_to_production",
    "FePourbaix",
    "her_line",
    "oer_line",
    "nernst_pH_line",
    "DepositionKinetics",
    "TafelBranch",
    "limiting_current_density",
    "CathodeBoundaryLayer",
    "BoundaryLayerState",
    "NernstPlanckFilm",
    "NernstPlanckState",
    "FilmProfile",
    "compare_support_levels",
    "PulseDepositionModel",
    "PulseWaveform",
    "PulseResult",
    "compare_dc_vs_pulse",
    "RandlesFit",
    "load_spectrum",
    "summarize_spectrum",
    "cpe_impedance",
    "warburg_impedance",
    "randles_impedance",
    "randles_cpe_impedance",
    "fit_randles_spectrum",
    "exchange_current_from_rct",
    "synthetic_randles_spectrum",
    "HullCellGeometry",
    "GravimetricFEResult",
    "hull_current_distribution",
    "summarize_hull_distribution",
    "current_density_window",
    "load_galvanostatic_trace",
    "load_gravimetry",
    "cathodic_charge_C",
    "gravimetric_faradaic_efficiency",
    "analyze_gravimetric_efficiency",
    "ElectrolyzerParams",
    "CAPEXModel",
    "OPEXModel",
    "LevelizedCost",
    "sensitivity_analysis",
    "compare_routes",
    "BENCHMARK_COSTS",
    # ── Anode / OER model ────────────────────────────────────────────
    "AnodeKinetics",
    "AnodeMaterial",
    "DSA_IRO2_TA2O5",
    "NICO_SPINEL",
    "NIFE_LDH",
    "PT_TI",
    "bubble_fraction",
    "bubble_resistance_multiplier",
    "concentration_overpotential_oer",
    "full_cell_voltage",
    "anode_eta_from_lookup",
    "E0_OER_ACIDIC",
    "E0_OER_ALKALINE",
    "E0_CER",
    # ── Phase III co-deposition ───────────────────────────────────────
    "GuglielmiCarbonIncorporation",
    "AnomalousFeNiKinetics",
    "PhaseIIICoDeposition",
    "build_phase3_model",
    # ── Phase IV durability / closed-loop model ───────────────────────
    "AnodeDurabilityParams",
    "ClosedLoopParams",
    "PhaseIVOperatingPoint",
    "PhaseIVResult",
    "PhaseIVClosedLoop",
    # ── Mechanical properties (new Phase III → structural) ────────────
    "MechanicalPropertiesModel",
    "MechanicalPropertiesResult",
    "MechanicalPropertiesParams",
    "GrainSizeParams",
    "estimate_grain_size_um",
    "hall_petch_yield_MPa",
    "solid_solution_strengthening_MPa",
    "carbon_dispersion_strengthening_MPa",
    "porosity_factor",
    "build_mechanical_model_from_phase3_result",
    # ── Process flow diagrams ─────────────────────────────────────────
    "generate_process_flow_diagram",
    "generate_detailed_flow_with_composition",
    # ── Carburization (post-deposition gaseous) ───────────────────────
    "CarburizationModel",
    "CarburizationParams",
    "CarburizationProfile",
    "CarburizationResult",
    "carbon_diffusivity_m2_s",
    "hardness_from_carbon_wt",
    "tempered_hardness",
    "estimate_carburizing_time_for_case_depth",
    # ── Pulse-aware co-deposition coupling ────────────────────────────
    "surface_pH_from_current",
    "surface_pH_from_pulse",
    "effective_mass_transport_enhancement",
]
