"""
models — Electrochemical, transport, transient pulse, and techno-economic modeling for aqueous electrowinning.
"""

from .electrochemistry import (
    CellVoltageModel,
    specific_energy_kWh_per_kg,
    specific_energy_kWh_per_t,
    production_rate_kg_per_hr,
    current_density_to_production,
)
from .pourbaix import (
    FePourbaix,
    her_line,
    oer_line,
    nernst_pH_line,
)
from .kinetics import (
    DepositionKinetics,
    TafelBranch,
    limiting_current_density,
)
from .boundary_layer import (
    CathodeBoundaryLayer,
    BoundaryLayerState,
)
from .transport import (
    NernstPlanckFilm,
    NernstPlanckState,
    FilmProfile,
    compare_support_levels,
)
from .pulse import (
    PulseDepositionModel,
    PulseWaveform,
    PulseResult,
    compare_dc_vs_pulse,
)
from .eis import (
    RandlesFit,
    load_spectrum,
    summarize_spectrum,
    cpe_impedance,
    warburg_impedance,
    randles_impedance,
    randles_cpe_impedance,
    fit_randles_spectrum,
    exchange_current_from_rct,
    synthetic_randles_spectrum,
)
from .hull_cell import (
    HullCellGeometry,
    GravimetricFEResult,
    hull_current_distribution,
    summarize_hull_distribution,
    current_density_window,
    load_galvanostatic_trace,
    load_gravimetry,
    cathodic_charge_C,
    gravimetric_faradaic_efficiency,
    analyze_gravimetric_efficiency,
)
from .technoeconomic import (
    ElectrolyzerParams,
    CAPEXModel,
    OPEXModel,
    LevelizedCost,
    sensitivity_analysis,
    compare_routes,
    BENCHMARK_COSTS,
)
from .anode import (
    AnodeKinetics,
    AnodeMaterial,
    DSA_IRO2_TA2O5,
    NICO_SPINEL,
    NIFE_LDH,
    PT_TI,
    bubble_fraction,
    bubble_resistance_multiplier,
    concentration_overpotential_oer,
    full_cell_voltage,
    anode_eta_from_lookup,
    E0_OER_ACIDIC,
    E0_OER_ALKALINE,
    E0_CER,
)
from .co_deposition import (
    GuglielmiCarbonIncorporation,
    AnomalousFeNiKinetics,
    PhaseIIICoDeposition,
    build_phase3_model,
    surface_pH_from_current,
    surface_pH_from_pulse,
    effective_mass_transport_enhancement,
)
from .impurity_codeposition import (
    ImpurityCoDeposition,
    BathKinetics,
    compare_bath_types,
    SULFATE_KINETICS,
    CHLORIDE_KINETICS,
    CU_HOT_SHORTNESS_WT,
)
from .closed_loop import (
    AnodeDurabilityParams,
    ClosedLoopParams,
    PhaseIVOperatingPoint,
    PhaseIVResult,
    PhaseIVClosedLoop,
)
from .mechanical_properties import (
    MechanicalPropertiesModel,
    MechanicalPropertiesResult,
    MechanicalPropertiesParams,
    GrainSizeParams,
    estimate_grain_size_um,
    hall_petch_yield_MPa,
    solid_solution_strengthening_MPa,
    carbon_dispersion_strengthening_MPa,
    porosity_factor,
    build_mechanical_model_from_phase3_result,
)
from .process_flow import (
    generate_process_flow_diagram,
    generate_detailed_flow_with_composition,
)
from .carburization import (
    CarburizationModel,
    CarburizationParams,
    CarburizationProfile,
    CarburizationResult,
    carbon_diffusivity_m2_s,
    hardness_from_carbon_wt,
    tempered_hardness,
    estimate_carburizing_time_for_case_depth,
)
from .carbon_potential import (
    carbon_potential_summary,
    carbon_activity_from_co_co2,
    carbon_activity_from_ch4_h2,
    carbon_wt_from_activity,
    austenite_max_carbon_wt_percent,
)
from .tempering import (
    AlloyComposition,
    martensite_start_C,
    retained_austenite_fraction_koistinen_marburger,
    hollomon_jaffe_parameter,
    tempered_hardness_hollomon_jaffe,
    tempering_curve,
    case_hardness_after_tempering,
    recommended_tempering_for_target_hv,
)
from .thermomechanical import (
    ThermomechanicalModel,
    ThermomechanicalParams,
    ThermomechanicalResult,
    RollingSchedule,
    jmak_fraction_recrystallized,
    recrystallized_grain_size_um,
    grain_growth_um,
    time_for_fraction,
)
from .foil_calibration import (
    FoilMeasurement,
    CaseDepthMeasurement,
    o2_probe_mv_to_pO2,
    pO2_to_carbon_activity_via_co_co2,
    fit_diffusivity_from_foil_data,
    fit_carbon_potential_offset,
    fit_tempering_softening,
    fit_mechanical_hall_petch,
)
from .pid import (
    generate_pid_overview,
    generate_pid_detailed,
)
from .scale_up import (
    wagner_number,
    primary_current_distribution,
    uniformity_index,
    secondary_current_distribution,
    SecondaryCurrentResult,
    boundary_layer_thickness,
    mass_transport_scaling,
    MassTransportResult,
    thermal_management,
    ThermalResult,
    optimize_geometry,
    GeometryResult,
    scale_up_analysis,
    ScaleUpResult,
)
from .hydrogen_embrittlement import (
    HDiffusionParams,
    TrapSiteParams,
    HESusceptibilityParams,
    BakeoutParams,
    h_diffusivity_m2_s,
    trap_binding_factor,
    trap_density_m3,
    effective_diffusivity_m2_s,
    hydrogen_uptake_from_electrolysis,
    he_susceptibility_index,
    bakeout_time_hr,
    bakeout_schedule,
    HEResult,
    HydrogenEmbrittlementModel,
    build_he_model_from_mechanical,
    synthetic_h_uptake_data,
)
from .membrane_fouling import (
    FoulingMechanism,
    HermiaModel,
    CleaningAgent,
    MembraneParams,
    FoulingRateParams,
    CleaningParams,
    CSTRFoulingCoupling,
    FluxDeclineResult,
    CleaningResult,
    FoulingSimulationResult,
    hermia_flux,
    MembraneFoulingModel,
    fouling_from_closed_loop_result,
    membrane_replacement_cost,
)
from .calibration_pipeline import (
    FitResult,
    fit_tafel_domain,
    fit_eis_domain,
    fit_hull_cell_domain,
    fit_diffusivity_domain,
    fit_carbon_potential_domain,
    fit_tempering_domain,
    fit_hall_petch_domain,
    CalibrationReport,
    write_calibrated_parameters,
    load_calibrated_params,
    apply_calibrated_params,
    ValidationResult,
    validate_calibration,
    generate_calibration_figures,
    run_calibration_pipeline,
)
from .pilot_costing import (
    EquipmentItem,
    six_tenths_scale,
    PilotCAPEXResult,
    estimate_capex,
    capex_at_all_scales,
    PilotOPEXModel,
    capex_sensitivity_tornado,
    capex_by_category,
    equipment_table,
)
from .pulse_optimization import (
    is_non_dominated,
    compute_pareto_front,
    PulseOptimizationSweep,
)
from .uncertainty.parameter_registry import (
    Parameter,
    registry_summary,
)
from .uncertainty.sample import (
    sobol_sequence,
    sample_parameters,
    parameter_matrix_to_kwargs,
)
from .uncertainty.specification import (
    Operator,
    Criticality,
    Specification,
    SpecResult,
    SpecReport,
    check_specifications,
    load_specs_from_yaml,
    load_specs_from_json,
    check_mc_specifications,
)
from .uncertainty.bayesian_calibration import (
    ParameterPrior,
    default_priors,
    CalibrationResult,
    MCMCResult,
    calibrate_ensemble,
    calibrate_mcmc,
    information_gain,
    optimal_next_experiment,
    generate_synthetic_observations,
    screening_forward_model,
)
from .bath_startup import (
    BathParams,
    BathSimulationResult,
    dissolved_o2_saturation_mol_L,
    g_per_L_to_mol_L,
    fe2_oxidation_rate,
    aa_reduction_rate,
    aa_autoxidation_rate,
    simulate_bath,
    recommend_ascorbic_loading,
    ascorbic_consumption_summary,
    sensitivity_ph,
    sensitivity_temperature,
)
from .speciation import (
    SolutionComposition,
    solve_speciation,
    speciation_temperature_sweep,
)
from .thermal_balance import (
    CellThermalParams,
    simulate_thermal_transient,
)
from .operating_window import (
    OperatingWindowConstraints,
    evaluate_operating_point,
    map_2d_operating_window,
)
from .experimental_matrix import (
    ChemicalRecipe,
    calculate_batch_recipe,
    predict_plating_run,
    generate_factorial_doe,
)
from .lca import (
    ElectricityMix,
    ChemicalSources,
    LCAResult,
    ComparisonRow,
    ComparisonTable,
    compute_lca,
    compare_routes as lca_compare_routes,
    sensitivity_to_electricity,
    breakeven_renewable_fraction,
)
from .hull_cell_fe import (
    DeltaProfile,
    HullCellFEConfig,
    HullCellFEResult,
    ZoneResult,
    appearance_from_fe,
    compare_fe_windows,
    fe_sensitivity_to_delta,
    hull_cell_fe_prediction,
)
from .transient import (
    UpsetType,
    TransientConfig,
    TransientResult,
    simulate_startup,
    simulate_shutdown,
    simulate_upset,
    recovery_time,
    damage_assessment,
)
from .process_control import (
    PIDParams,
    PIDController,
    CascadeController,
    default_loops,
    simulate_first_order_plant,
    LoopResult,
    simulate_loop,
    tuning_sensitivity,
    loop_summary_table,
)
from .digital_twin import (
    SensorSpec,
    TwinState,
    PredictionEnvelope,
    Anomaly,
    generate_synthetic_readings,
    ExtendedKalmanFilter,
    AnomalyDetector,
    DigitalTwin,
)
from .feedstock_logistics import (
    RawMaterial,
    DesignPoint,
    MaterialLineItem,
    MaterialBalance,
    material_balance,
    ImpurityLimit,
    RecyclingEconomics,
    electrolyte_recycling,
    LocationData,
    LocationWeight,
    LocationScore,
    LocationRanking,
    site_score,
    compare_locations,
    SensitivityResult,
    electricity_sensitivity,
)
from .twin_physics import (
    CellProcessModel,
    ProcessPrediction,
    default_process_model,
    generate_physics_readings,
)
from .crate import (
    Crate,
    CrateConfig,
    CrateSpec,
    WindLoad,
    GroundSpec,
    EnvironmentalLoads,
    CrateVerdict,
    evaluate_crate,
)
from .system_twin import (
    CredibilityVector,
    SystemTwinReport,
    evaluate_system_twin,
    evaluate_all_sites as evaluate_all_system_twins,
    LEGACY_THREE,
)
from .dark_mill import (
    SiteDefinition,
    ClimateSpec,
    GridSpec,
    StackDesign,
    MassBalance,
    SiteReport,
    size_dark_mill,
    site_to_crate_config,
    evaluate_crate_for_site,
    EXAMPLE_SITES,
    run_site,
    run_all_sites,
    comparison_table,
)
from .operating_twin import (
    OperatingTwin,
    TwinConfig,
    SensorSnapshot,
    TwinMode,
    TwinState,
    ControlCommand,
)

__all__ = [
    "CellVoltageModel",
    "specific_energy_kWh_per_kg",
    "specific_energy_kWh_per_t",
    "production_rate_kg_per_hr",
    "current_density_to_production",
    "FePourbaix",
    "her_line",
    "oer_line",
    "nernst_pH_line",
    "DepositionKinetics",
    "TafelBranch",
    "limiting_current_density",
    "CathodeBoundaryLayer",
    "BoundaryLayerState",
    "NernstPlanckFilm",
    "NernstPlanckState",
    "FilmProfile",
    "compare_support_levels",
    "PulseDepositionModel",
    "PulseWaveform",
    "PulseResult",
    "compare_dc_vs_pulse",
    "RandlesFit",
    "load_spectrum",
    "summarize_spectrum",
    "cpe_impedance",
    "warburg_impedance",
    "randles_impedance",
    "randles_cpe_impedance",
    "fit_randles_spectrum",
    "exchange_current_from_rct",
    "synthetic_randles_spectrum",
    "HullCellGeometry",
    "GravimetricFEResult",
    "hull_current_distribution",
    "summarize_hull_distribution",
    "current_density_window",
    "load_galvanostatic_trace",
    "load_gravimetry",
    "cathodic_charge_C",
    "gravimetric_faradaic_efficiency",
    "analyze_gravimetric_efficiency",
    "ElectrolyzerParams",
    "CAPEXModel",
    "OPEXModel",
    "LevelizedCost",
    "sensitivity_analysis",
    "compare_routes",
    "BENCHMARK_COSTS",
    # ── Anode / OER model ────────────────────────────────────────────
    "AnodeKinetics",
    "AnodeMaterial",
    "DSA_IRO2_TA2O5",
    "NICO_SPINEL",
    "NIFE_LDH",
    "PT_TI",
    "bubble_fraction",
    "bubble_resistance_multiplier",
    "concentration_overpotential_oer",
    "full_cell_voltage",
    "anode_eta_from_lookup",
    "E0_OER_ACIDIC",
    "E0_OER_ALKALINE",
    "E0_CER",
    # ── Phase III co-deposition ───────────────────────────────────────
    "GuglielmiCarbonIncorporation",
    "AnomalousFeNiKinetics",
    "PhaseIIICoDeposition",
    "build_phase3_model",
    # ── Impurity co-deposition ───────────────────────────────────────
    "ImpurityCoDeposition",
    "BathKinetics",
    "compare_bath_types",
    "SULFATE_KINETICS",
    "CHLORIDE_KINETICS",
    "CU_HOT_SHORTNESS_WT",
    # ── Phase IV durability / closed-loop model ───────────────────────
    "AnodeDurabilityParams",
    "ClosedLoopParams",
    "PhaseIVOperatingPoint",
    "PhaseIVResult",
    "PhaseIVClosedLoop",
    # ── Mechanical properties (new Phase III → structural) ────────────
    "MechanicalPropertiesModel",
    "MechanicalPropertiesResult",
    "MechanicalPropertiesParams",
    "GrainSizeParams",
    "estimate_grain_size_um",
    "hall_petch_yield_MPa",
    "solid_solution_strengthening_MPa",
    "carbon_dispersion_strengthening_MPa",
    "porosity_factor",
    "build_mechanical_model_from_phase3_result",
    # ── Process flow diagrams ─────────────────────────────────────────
    "generate_process_flow_diagram",
    "generate_detailed_flow_with_composition",
    # ── Carburization (post-deposition gaseous) ───────────────────────
    "CarburizationModel",
    "CarburizationParams",
    "CarburizationProfile",
    "CarburizationResult",
    "carbon_diffusivity_m2_s",
    "hardness_from_carbon_wt",
    "tempered_hardness",
    "estimate_carburizing_time_for_case_depth",
    # ── Carbon potential (gas atmosphere) ─────────────────────────────
    "carbon_potential_summary",
    "carbon_activity_from_co_co2",
    "carbon_activity_from_ch4_h2",
    "carbon_wt_from_activity",
    "austenite_max_carbon_wt_percent",
    # ── Tempering & retained austenite ────────────────────────────────
    "AlloyComposition",
    "martensite_start_C",
    "retained_austenite_fraction_koistinen_marburger",
    "hollomon_jaffe_parameter",
    "tempered_hardness_hollomon_jaffe",
    "tempering_curve",
    "case_hardness_after_tempering",
    "recommended_tempering_for_target_hv",
    # ── Thermomechanical (roll + recrystallize) ───────────────────────
    "ThermomechanicalModel",
    "ThermomechanicalParams",
    "ThermomechanicalResult",
    "RollingSchedule",
    "jmak_fraction_recrystallized",
    "recrystallized_grain_size_um",
    "grain_growth_um",
    "time_for_fraction",
    # ── Foil calibration & O2 probe ───────────────────────────────────
    "FoilMeasurement",
    "CaseDepthMeasurement",
    "o2_probe_mv_to_pO2",
    "pO2_to_carbon_activity_via_co_co2",
    "fit_diffusivity_from_foil_data",
    "fit_carbon_potential_offset",
    "fit_tempering_softening",
    "fit_mechanical_hall_petch",
    # ── Pilot P&ID ────────────────────────────────────────────────────
    "generate_pid_overview",
    "generate_pid_detailed",
    # ── Pulse-aware co-deposition coupling ────────────────────────────
    "surface_pH_from_current",
    "surface_pH_from_pulse",
    "effective_mass_transport_enhancement",
    # ── Scale-up model ───────────────────────────────────────────────
    "wagner_number",
    "primary_current_distribution",
    "uniformity_index",
    "secondary_current_distribution",
    "SecondaryCurrentResult",
    "boundary_layer_thickness",
    "mass_transport_scaling",
    "MassTransportResult",
    "thermal_management",
    "ThermalResult",
    "optimize_geometry",
    "GeometryResult",
    "scale_up_analysis",
    "ScaleUpResult",
    # ── Hydrogen embrittlement ───────────────────────────────────────
    "HDiffusionParams",
    "TrapSiteParams",
    "HESusceptibilityParams",
    "BakeoutParams",
    "h_diffusivity_m2_s",
    "trap_binding_factor",
    "trap_density_m3",
    "effective_diffusivity_m2_s",
    "hydrogen_uptake_from_electrolysis",
    "he_susceptibility_index",
    "bakeout_time_hr",
    "bakeout_schedule",
    "HEResult",
    "HydrogenEmbrittlementModel",
    "build_he_model_from_mechanical",
    "synthetic_h_uptake_data",
    # ── Membrane fouling ─────────────────────────────────────────────
    "FoulingMechanism",
    "HermiaModel",
    "CleaningAgent",
    "MembraneParams",
    "FoulingRateParams",
    "CleaningParams",
    "CSTRFoulingCoupling",
    "FluxDeclineResult",
    "CleaningResult",
    "FoulingSimulationResult",
    "hermia_flux",
    "MembraneFoulingModel",
    "fouling_from_closed_loop_result",
    "membrane_replacement_cost",
    # ── Calibration pipeline ─────────────────────────────────────────
    "FitResult",
    "fit_tafel_domain",
    "fit_eis_domain",
    "fit_hull_cell_domain",
    "fit_diffusivity_domain",
    "fit_carbon_potential_domain",
    "fit_tempering_domain",
    "fit_hall_petch_domain",
    "CalibrationReport",
    "write_calibrated_parameters",
    "load_calibrated_params",
    "apply_calibrated_params",
    "ValidationResult",
    "validate_calibration",
    "generate_calibration_figures",
    "run_calibration_pipeline",
    # ── Pilot costing ────────────────────────────────────────────────
    "EquipmentItem",
    "six_tenths_scale",
    "PilotCAPEXResult",
    "estimate_capex",
    "capex_at_all_scales",
    "PilotOPEXModel",
    "capex_sensitivity_tornado",
    "capex_by_category",
    "equipment_table",
    # ── Pulse optimization ───────────────────────────────────────────
    "is_non_dominated",
    "compute_pareto_front",
    "PulseOptimizationSweep",
    # ── Uncertainty: parameter registry ──────────────────────────────
    "Parameter",
    "registry_summary",
    # ── Uncertainty: sampling ────────────────────────────────────────
    "sobol_sequence",
    "sample_parameters",
    "parameter_matrix_to_kwargs",
    # ── Uncertainty: specifications ──────────────────────────────────
    "Operator",
    "Criticality",
    "Specification",
    "SpecResult",
    "SpecReport",
    "check_specifications",
    "load_specs_from_yaml",
    "load_specs_from_json",
    "check_mc_specifications",
    # ── Uncertainty: Bayesian calibration ────────────────────────────
    "ParameterPrior",
    "default_priors",
    "CalibrationResult",
    "MCMCResult",
    "calibrate_ensemble",
    "calibrate_mcmc",
    "information_gain",
    "optimal_next_experiment",
    "generate_synthetic_observations",
    "screening_forward_model",
    # ── Bath startup kinetics ─────────────────────────────────────────
    "BathParams",
    "BathSimulationResult",
    "dissolved_o2_saturation_mol_L",
    "g_per_L_to_mol_L",
    "fe2_oxidation_rate",
    "aa_reduction_rate",
    "aa_autoxidation_rate",
    "simulate_bath",
    "recommend_ascorbic_loading",
    "ascorbic_consumption_summary",
    "sensitivity_ph",
    "sensitivity_temperature",
    # ── Speciation & Activity ─────────────────────────────────────────
    "SolutionComposition",
    "solve_speciation",
    "speciation_temperature_sweep",
    # ── Thermal balance ──────────────────────────────────────────────
    "CellThermalParams",
    "simulate_thermal_transient",
    # ── Operating window ──────────────────────────────────────────────
    "OperatingWindowConstraints",
    "evaluate_operating_point",
    "map_2d_operating_window",
    "ChemicalRecipe",
    "calculate_batch_recipe",
    "predict_plating_run",
    "generate_factorial_doe",
    # ── Life cycle assessment ─────────────────────────────────────────
    "ElectricityMix",
    "ChemicalSources",
    "LCAResult",
    "ComparisonRow",
    "ComparisonTable",
    "compute_lca",
    "lca_compare_routes",
    "sensitivity_to_electricity",
    "breakeven_renewable_fraction",
    # ── Hull-cell FE coupling ─────────────────────────────────────────
    "DeltaProfile",
    "HullCellFEConfig",
    "HullCellFEResult",
    "ZoneResult",
    "appearance_from_fe",
    "compare_fe_windows",
    "fe_sensitivity_to_delta",
    "hull_cell_fe_prediction",
    # ── Transient / upset operations ──────────────────────────────────
    "UpsetType",
    "TransientConfig",
    "TransientResult",
    "simulate_startup",
    "simulate_shutdown",
    "simulate_upset",
    "recovery_time",
    "damage_assessment",
    # ── Process control ───────────────────────────────────────────────
    "PIDParams",
    "PIDController",
    "CascadeController",
    "default_loops",
    "simulate_first_order_plant",
    "LoopResult",
    "simulate_loop",
    "tuning_sensitivity",
    "loop_summary_table",
    # ── Digital twin (state estimation) ───────────────────────────────
    "SensorSpec",
    "TwinState",
    "PredictionEnvelope",
    "Anomaly",
    "generate_synthetic_readings",
    "ExtendedKalmanFilter",
    "AnomalyDetector",
    "DigitalTwin",
    # ── Feedstock logistics ───────────────────────────────────────────
    "RawMaterial",
    "DesignPoint",
    "MaterialLineItem",
    "MaterialBalance",
    "material_balance",
    "ImpurityLimit",
    "RecyclingEconomics",
    "electrolyte_recycling",
    "LocationData",
    "LocationWeight",
    "LocationScore",
    "LocationRanking",
    "site_score",
    "compare_locations",
    "SensitivityResult",
    "electricity_sensitivity",
    # ── Physics process model (digital twin measurement model) ────────
    "CellProcessModel",
    "ProcessPrediction",
    "default_process_model",
    "generate_physics_readings",
    # ── Crate structural/environmental model ───────────────────────────
    "Crate",
    "CrateConfig",
    "CrateSpec",
    "WindLoad",
    "GroundSpec",
    "EnvironmentalLoads",
    "CrateVerdict",
    "evaluate_crate",
    # ── Whole-system twin (process + crate + site) ────────────────────
    "CredibilityVector",
    "SystemTwinReport",
    "evaluate_system_twin",
    "evaluate_all_system_twins",
    "LEGACY_THREE",
    # ── Dark mill (site definition + sizing + crate coupling) ─────────
    "SiteDefinition",
    "ClimateSpec",
    "GridSpec",
    "StackDesign",
    "MassBalance",
    "SiteReport",
    "size_dark_mill",
    "site_to_crate_config",
    "evaluate_crate_for_site",
    "EXAMPLE_SITES",
    "run_site",
    "run_all_sites",
    "comparison_table",
    # ── Operating twin (safety + environmental safe-state) ────────────
    "OperatingTwin",
    "TwinConfig",
    "SensorSnapshot",
    "TwinMode",
    "TwinState",
    "ControlCommand",
]
